In [68]:
import pandas as pd
import numpy as np

from datetime import datetime
import random

In [151]:
data_csv = '/home/grzegorz/Desktop/Database/Project/data.csv' 
df_names = pd.read_csv(data_csv, sep=',')

club_csv = '/home/grzegorz/Desktop/Database/Project/clubs.csv' 
df_clubs = pd.read_csv(club_csv, sep=',')

In [155]:
df_clubs

,Club,Location,Capacity,stadium_id
0,Arka Gdynia,Gdynia\tStadion GOSiR,15139,0
1,Bruk-Bet Termalica Nieciecza,Nieciecza\tStadion Termaliki,4595,1
2,Cracovia,Marshal Józef Piłsudski,15016,2
3,Górnik Zabrze,Ernest Pohl,24413,3
4,Jagiellonia Białystok,Białystok City Stadium,22372,4
5,Korona Kielce,Kolporter Arena,15550,5
6,Lech Poznań,INEA Stadion,43269,6
7,Lechia Gdańsk,Energa Gdańsk,43615,7
8,Legia Warsawa,Polish Army Stadium,31800,8
9,Piast Gliwice,Gliwice\tStadion Piast,10037,9
10,Pogoń Szczecin,Stadion Florian Krygier,18027,10
11,Sandecja Nowy Sącz\tNieciecza,Termaliki Bruk-Bet,4595,11
12,Wisła Krakówa,Henryk Reyman Stadium,33268,12
13,Wisła Płock\tPłock,Kazimierz Górski,10978,13
14,Zagłębie Lubin,Stadion Zagłębia Lubin,16068,14
15,Śląsk Wrocław,Stadion Wrocław,42771,15

In [153]:
trainer_header = ['Name', 'DOB', 'Club', 'trainer_id']
df_trainer = pd.DataFrame(columns=trainer_header)

# trainer_header = ['Club', 'Location', 'Capacity']
# df_clubs = pd.DataFrame(columns=trainer_header)

In [156]:
df_trainer['Name'] = df_names['Trainer'].iloc[0:50]
df_trainer['DOB'] = df_names['Trainer_DOB'].iloc[0:50]
tr = np.random.randint(len(df_clubs), size=len(df_trainer))
df_trainer['Club'] = df_clubs['Club'].iloc[tr].values
df_trainer['trainer_id'] = np.arange(len(df_trainer))
df_trainer

                   Name       DOB                           Club  trainer_id
0            Caryn Rich  04-14-46                    Arka Gdynia           0
1         Whitney Klein  04-03-77                  Korona Kielce           1
2       Patricia Powers  12-11-46             Wisła Płock\tPłock           2
3       Winifred Vinson  01-18-74                  Legia Warsawa           3
4      Mechelle Griffin  06-20-66   Bruk-Bet Termalica Nieciecza           4
5             Rana Kidd  09-29-77                  Śląsk Wrocław           5
6        Allegra Monroe  09-01-68                  Piast Gliwice           6
7         Kiona Sanders  11-19-44                  Wisła Krakówa           7
8         Chanda Cooley  08-22-67   Bruk-Bet Termalica Nieciecza           8
9         Desiree Walsh  06-11-57                       Cracovia           9
10          Eve Solomon  12-29-80                  Wisła Krakówa          10
11        Laurel Rhodes  08-03-64                  Piast Gliwice          11
12       Felicia Franks  09-05-70             Wisła Płock\tPłock          12
13       Aphrodite Rush  09-17-50                    Arka Gdynia          13
14         Maia Huffman  05-07-61                  Wisła Krakówa          14
15          Inga Mccray  01-29-89          Jagiellonia Białystok          15
16       Katell Edwards  10-22-51                  Piast Gliwice          16
17      Clare Castaneda  03-03-57                    Lech Poznań          17
18       Rebekah Curtis  07-18-89                  Śląsk Wrocław          18
19         Iona Calhoun  11-21-90                    Arka Gdynia          19
20        Tanisha Finch  02-16-68   Bruk-Bet Termalica Nieciecza          20
21        Lesley Herman  10-04-62                  Legia Warsawa          21
22      Kirsten Webster  03-12-64                    Arka Gdynia          22
23      Sigourney Quinn  01-08-58                  Lechia Gdańsk          23
24          Medge Reese  11-28-90                    Lech Poznań          24
25         May Hamilton  06-10-62                  Legia Warsawa          25
26          Nell Chavez  01-01-63                       Cracovia          26
27      Delilah Mccarty  01-14-45  Sandecja Nowy Sącz\tNieciecza          27
28              Uma Key  10-23-58                  Piast Gliwice          28
29        Alexa Mcclain  10-10-61                  Śląsk Wrocław          29
30       Brynne Fuentes  02-25-77                  Piast Gliwice          30
31         Sacha Gamble  03-20-49                 Pogoń Szczecin          31
32    Candice Valentine  05-18-79                  Piast Gliwice          32
33     Kirestin Salinas  01-17-80                  Śląsk Wrocław          33
34          Dara Hunter  08-16-44                    Arka Gdynia          34
35       Jocelyn Holman  08-15-83                  Korona Kielce          35
36           Iona Kline  05-14-68          Jagiellonia Białystok          36
37         Desirae Mann  04-21-69                    Lech Poznań          37
38       Tamekah Rivera  08-23-71                  Wisła Krakówa          38
39        Sierra Malone  02-13-60                  Śląsk Wrocław          39
40         Ariana Britt  08-01-87   Bruk-Bet Termalica Nieciecza          40
41         Jana Hopkins  08-02-51                  Górnik Zabrze          41
42         Farrah Olsen  02-02-73                       Cracovia          42
43           Jena Hicks  02-02-63   Bruk-Bet Termalica Nieciecza          43
44  Priscilla Maldonado  02-06-59                    Arka Gdynia          44
45        Skyler Waller  11-09-75          Jagiellonia Białystok          45
46         Yvette Small  05-25-90                    Lech Poznań          46
47         Nyssa Hayden  07-19-48                  Śląsk Wrocław          47
48            Erica Key  03-28-68                  Śląsk Wrocław          48
49         Maggy Rivera  08-11-74                  Legia Warsawa          49

In [154]:
# np.random.randint(len(df_clubs), size=len(df_trainer))
df_clubs['stadium_id'] = np.arange(len(df_clubs))
df_clubs

,Club,Location,Capacity,stadium_id
0,Arka Gdynia,Gdynia\tStadion GOSiR,15139,0
1,Bruk-Bet Termalica Nieciecza,Nieciecza\tStadion Termaliki,4595,1
2,Cracovia,Marshal Józef Piłsudski,15016,2
3,Górnik Zabrze,Ernest Pohl,24413,3
4,Jagiellonia Białystok,Białystok City Stadium,22372,4
5,Korona Kielce,Kolporter Arena,15550,5
6,Lech Poznań,INEA Stadion,43269,6
7,Lechia Gdańsk,Energa Gdańsk,43615,7
8,Legia Warsawa,Polish Army Stadium,31800,8
9,Piast Gliwice,Gliwice\tStadion Piast,10037,9
10,Pogoń Szczecin,Stadion Florian Krygier,18027,10
11,Sandecja Nowy Sącz\tNieciecza,Termaliki Bruk-Bet,4595,11
12,Wisła Krakówa,Henryk Reyman Stadium,33268,12
13,Wisła Płock\tPłock,Kazimierz Górski,10978,13
14,Zagłębie Lubin,Stadion Zagłębia Lubin,16068,14
15,Śląsk Wrocław,Stadion Wrocław,42771,15

In [63]:
runner_header = ['Name', 'DOB', 'Club', 'gender','trener_id']
# Male
df_runner_M = pd.DataFrame(columns=runner_header)
df_runner_M['Name'] = df_names['Runner_male'].iloc[0:300]
df_runner_M['DOB'] = df_names['Runner_male_DOB'].iloc[0:300]
tr = np.random.randint(len(df_clubs), size=len(df_runner_M))
df_runner_M['Club'] = df_clubs['Club'].iloc[tr].values
tr = np.random.randint(len(df_trainer), size=len(df_runner_M))
df_runner_M['trener_id'] = df_trainer['trainer_id'].iloc[tr].values
df_runner_M['gender'] = np.array(['M']*(len(df_runner_M)))

In [64]:
# Female
df_runner_F = pd.DataFrame(columns=runner_header)
df_runner_F['Name'] = df_names['Runner_female'].iloc[0:300]
df_runner_F['DOB'] = df_names['Runner_male_DOB.1'].iloc[0:300]
tr = np.random.randint(len(df_clubs), size=len(df_runner_F))
df_runner_F['Club'] = df_clubs['Club'].iloc[tr].values
tr = np.random.randint(len(df_trainer), size=len(df_runner_F))
df_runner_F['trener_id'] = df_trainer['trainer_id'].iloc[tr].values
df_runner_F['gender'] = np.array(['F']*(len(df_runner_F)))

In [67]:
# print(df_runner_M)
df_runner = pd.concat([df_runner_M, df_runner_F])

In [112]:
# Building the Competition table
competition_header = ['stadium_id', 'date', 'attendence', 'weather']
df_competition = pd.DataFrame(columns=competition_header)
# we generate 100 100 comeptition
# weather types:
# Rainy- R
# Sunny- S
# Cloudy- K
# Hot- H
# Cold- C
# Dry- D
# Wet- W
weather_types = ['R', 'S', 'K', 'H', 'C', 'D', 'W']
wt = list()
date_list = list()
att_list = list()
for i in np.arange(1,100): 
    n = random.randint(0, (len(weather_types)-1))
    wt.append(weather_types[n])
    year = random.randint(2015, 2018)
    month = random.randint(4, 8)
    day = random.randint(1, 30)
    comp_date = datetime(year, month, day)
    date_list.append(comp_date)
    att_list.append(random.randint(1000, 3000))
    
    
df_competition['date'] = date_list
df_competition['attendence'] = att_list
df_competition['weather'] = wt
tr = np.random.randint(len(df_clubs), size=len(df_competition))
df_competition['stadium_id'] = df_clubs['stadium_id'].iloc[tr].values
df_competition['competition_id'] = np.arange(len(df_competition))

In [144]:
# Generate the Results Table
result_header = ['Name', 'DOB', 'Club', 'gender', 'result', 'discipline', 'date', 'competition_id','result_id']
df_result = pd.DataFrame(columns=result_header)
discip_head = np.array(['100', '200', '400', '800', '1000', '1500'])
n = 100000
tr = np.random.randint(len(df_runner), size=n)
# for i in np.arange(1,100): 
#     n = random.randint(0, (len(weather_types)-1))
df_result['Name'] = df_runner['Name'].iloc[tr].values
df_result['DOB'] = df_runner['DOB'].iloc[tr].values
df_result['Club'] = df_runner['Club'].iloc[tr].values
df_result['gender'] = df_runner['gender'].iloc[tr].values
tr = np.random.randint(len(discip_head), size=n)
df_result['discipline'] = discip_head[tr]

tr = np.random.randint(len(df_competition), size=n)
df_result['date'] = df_competition['date'].iloc[tr].values
df_result['competition_id'] = df_competition['competition_id'].iloc[tr].values
df_result['result_id'] = np.arange(len(df_result))

results = list()
for index, row in df_result.iterrows():
    if row['gender']=='M':
        if row['discipline']=='100':
            res = np.random.randint(10,13) + np.random.randint(0,100)/100
        elif row['discipline']=='200':
            res = np.random.randint(20,23) + np.random.randint(0,100)/100
        elif row['discipline']=='400':
            res = np.random.randint(45,51) + np.random.randint(0,100)/100
        elif row['discipline']=='800':
            res = np.random.randint(105,115) + np.random.randint(0,100)/100
        elif row['discipline']=='1000':
            res = np.random.randint(140,160) + np.random.randint(0,100)/100
        else:
            res = np.random.randint(210,240) + np.random.randint(0,100)/100
    else:
        if row['discipline']=='100':
            res = np.random.randint(12,15) + np.random.randint(0,100)/100
        elif row['discipline']=='200':
            res = np.random.randint(23,26) + np.random.randint(0,100)/100
        elif row['discipline']=='400':
            res = np.random.randint(51,57) + np.random.randint(0,100)/100
        elif row['discipline']=='800':
            res = np.random.randint(125,140) + np.random.randint(0,100)/100
        elif row['discipline']=='1000':
            res = np.random.randint(165,195) + np.random.randint(0,100)/100
        else:
            res = np.random.randint(245,270) + np.random.randint(0,100)/100
    # Female
    results.append(res)
df_result['result'] = results

In [160]:
df_result_60 = df_result[df_result['competition_id']==60]
df_result = df_result[df_result['competition_id']!=60]
df_result_61 = df_result[df_result['competition_id']==61]
df_result = df_result[df_result['competition_id']!=61]

In [169]:
# Saving the results
club_csv = '/home/grzegorz/Desktop/Database/Project/initial_db/stadion,csv'
trainer_csv = '/home/grzegorz/Desktop/Database/Project/initial_db/trainer.csv'
runner_csv = '/home/grzegorz/Desktop/Database/Project/initial_db/runner.csv'
compet_csv = '/home/grzegorz/Desktop/Database/Project/initial_db/compet.csv'
result_csv = '/home/grzegorz/Desktop/Database/Project/initial_db/result.csv'
result60_csv = '/home/grzegorz/Desktop/Database/Project/initial_db/result60.csv'
result61_csv = '/home/grzegorz/Desktop/Database/Project/initial_db/result61.csv'

df_clubs.to_csv(club_csv, sep=',')
df_trainer.to_csv(trainer_csv, sep=',')
df_runner.to_csv(runner_csv, sep=',')
df_competition.to_csv(compet_csv, sep=',')
df_result.to_csv(result_csv, sep=',')

df_result_60.to_csv(result60_csv, sep=',')
df_result_61.to_csv(result61_csv, sep=',')

In [168]:
df_clubs

,Club,Location,Capacity,stadium_id
0,Arka Gdynia,Gdynia\tStadion GOSiR,15139,0
1,Bruk-Bet Termalica Nieciecza,Nieciecza\tStadion Termaliki,4595,1
2,Cracovia,Marshal Józef Piłsudski,15016,2
3,Górnik Zabrze,Ernest Pohl,24413,3
4,Jagiellonia Białystok,Białystok City Stadium,22372,4
5,Korona Kielce,Kolporter Arena,15550,5
6,Lech Poznań,INEA Stadion,43269,6
7,Lechia Gdańsk,Energa Gdańsk,43615,7
8,Legia Warsawa,Polish Army Stadium,31800,8
9,Piast Gliwice,Gliwice\tStadion Piast,10037,9
10,Pogoń Szczecin,Stadion Florian Krygier,18027,10
11,Sandecja Nowy Sącz\tNieciecza,Termaliki Bruk-Bet,4595,11
12,Wisła Krakówa,Henryk Reyman Stadium,33268,12
13,Wisła Płock\tPłock,Kazimierz Górski,10978,13
14,Zagłębie Lubin,Stadion Zagłębia Lubin,16068,14
15,Śląsk Wrocław,Stadion Wrocław,42771,15